version: '3.8'

services:
  pocketbase:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./pb_data:/pb/pb_data
      # Uncomment below lines if you want to use migrations and hooks
      # - ./pb_migrations:/pb/pb_migrations
      # - ./pb_hooks:/pb/pb_hooks
    restart: unless-stopped
